### ISSUE TITLE
Encoder swap must be configurable

### ISSUE THREAD

**Issue by katodo** [officinerobotiche/uNAV.X#17]
For each encoder QEI module the QEIxCONbits.SWPAB  bit must be configurable to simplify encoder connection.

**Comment by rbonghi** [comment]
Now I modified a old message **parameter_motors** and I dived in two struct, the first one, with only parameter associated ad unicycle platform and the last with parameters associated only at motors:
```c
/**
 * Parameters definition for unicycle robot:
 * - radius (left and right)
 * - wheelbase
 * - minimal space for odometry
 */
typedef struct parameter_unicycle {
    float radius_r;
    float radius_l;
    float wheelbase;
    float sp_min;
} parameter_unicycle_t;
#define LNG_PARAMETER_UNICYCLE sizeof(parameter_unicycle_t)
```
In new structure **parameter_motor_t** you can modified the encoder swap and default level Enable bits.
```c
/**
 * Parameter definiton for motor:
 * - k_vel
 * - k_ang
 * - boolean encoder swap
 * - boolean set enable
 */
typedef struct parameter_motor {
    float k_vel;
    float k_ang;
    uint8_t encoder_swap;
    uint8_t enable_set;
} parameter_motor_t;
#define LNG_PARAMETER_MOTOR sizeof(parameter_motor_t)
```

I update serial_bridge repository https://github.com/officinerobotiche/serial_bridge with new feature.
If you like to try this feature switch branch to https://github.com/officinerobotiche/uNAV.X/tree/feature/message_pin_conf **feature/message_pin_conf** (the same on serial_bridge) and test.

**Comment by Myzhar** [comment]
This is a good choice. Please add a comment for each variable of the structure to describe their functions. This is important for motor parameters

**Comment by rbonghi** [comment]
Thx @Myzhar , In the real repository I wrote a link to officinerobotiche wiki's https://github.com/officinerobotiche/uNAV.X/blob/feature/message_pin_conf/includes/packet/motion.h#L117 to understand and set correct value on parameters.

Now I must write the page on wiki: http://wiki.officinerobotiche.it/index.php?title=Robot_configuration_guide 
:+1:

**Comment by katodo** [comment]
I'm testing encoder_swap functionality but don't work.
In yaml file I'm changing "encoder_swap" pararameter for test:

> Left: {k_vel: 27925268.0, k_ang: 0.00017453292093705386, encoder_swap: 1, default_enable: 0}
> Right: {k_vel: 27925268.0, k_ang: 0.00017453292093705386, encoder_swap: 0, default_enable: 0}

I've placed MPLABx in debug mode on parsing_other_messages.c row 92 and 97 and in **info->packet.parameter_motor.encoder_swap** variable I don't see any change in relation with yaml change.

Obviously, after any change of https://github.com/officinerobotiche/example_robot_ros/blob/master/example_robot.yaml file, I close roscore and any other node.

**Comment by rbonghi** [comment]
The problem is in repository serial_bridge: https://github.com/officinerobotiche/serial_bridge/tree/feature/message_pin_conf

**Comment by rbonghi** [comment]
Solve with 7c521dc7b8a8784a64661951bae9efc6258d1f5d
