### ISSUE TITLE
i2c EEPROM control

### ISSUE THREAD

**Issue by rbonghi** [officinerobotiche/uNAV.X#20]
EEPROM control for uNAV

**Comment by rbonghi** [comment]
I suggest @guiott to update your branch to last develop commit.
The branch https://github.com/officinerobotiche/uNAV.X/tree/feature/i2c_communication it is very oldest!

If you have problem to update the branch (merge develop in feature/i2c_communication) call me or @Myzhar

**Comment by guiott** [comment]
ok


> Il giorno 07/gen/2015, alle ore 10:56, Raffaello Bonghi <notifications@github.com> ha scritto:
> 
> I suggest @guiott <https://github.com/guiott> to update your branch to last develop commit.
> The branch https://github.com/officinerobotiche/uNAV.X/tree/feature/i2c_communication <https://github.com/officinerobotiche/uNAV.X/tree/feature/i2c_communication> it is very oldest!
> 
> If you have problem to update the branch (merge develop in feature/i2c_communication) call me or @Myzhar <https://github.com/Myzhar>
> —
> Reply to this email directly or view it on GitHub <https://github.com/officinerobotiche/uNAV.X/issues/20#issuecomment-69000458>.
> 

___________________
http://www.guiott.com/
