### ISSUE TITLE
Speed reversion over a limit

### ISSUE THREAD

**Issue by Myzhar** [officinerobotiche/uNAV.X#25]
This is an amazing bug:
if I increase the speed of the robot, at a certain point the wheels start spinning at the same speed, but in the opposite direction!

I could reach this point modifying the "constraint" values in the "yaml" file 

@katodo @rbonghi

**Comment by Myzhar** [comment]
After the recent changes this problem came out again.
It happens when my robot overcomes the speed of 1.1m/sec as setpoint (impossible since my physic limit is about 0.8 m/sec)

Considering a wheel radius of about 0.035 m when we have a rotation speed of 32.767 rad/sec, the linear speed is about 1.15m/sec... The inversion speed!

The problem is not present using the PID Tuner, so there is an overflow issue converting from m/sec to rad/sec.

We must set a saturation point for setpoint major than 32.767 rad/sec.

What I cannot understand is that the saturation is present... but does not work as expected...

**Comment by rbonghi** [comment]
This issue is the same of #40 .
