### ISSUE TITLE
Suspected overflow problem with K_ang parameter very low

### ISSUE THREAD

**Issue by katodo** [officinerobotiche/uNAV.X#26]
My motor have 43,3:1 ratio and 400cpr encoder, with Walter RobotParamCalculator https://github.com/officinerobotiche/RobotParamCalculator I obtain this value:
* k_vel: 14510820.570854
* k_ang:  0.000091

but with this value PID tuning is impossible.
I'm testing  http://automatica.ing.unibs.it/mco/tco/3_pid/zn.html algoritm with Ki and Kd = 0 and changing only Kp parameter.
I run **rosrun serial_bridge drive_bridge_node** to keep ENABLED bridge
and with this rostopic comman I give velocity "step":
**rostopic pub -1 /robot/command/velocity geometry_msgs/Twist -- '[0.5, 0.0, 0.0]' '[0.0, 0.0, 0.0]'**
**rostopic pub -1 /robot/command/velocity geometry_msgs/Twist -- '[-0.5, 0.0, 0.0]' '[0.0, 0.0, 0.0]'**

this is the result:

>**Left**: {P: 0.34, I: 0.0, D: 0.0}
>**Right**: {P: 0.34, I: 0.0, D: 0.0}
![pid_034](https://cloud.githubusercontent.com/assets/6282985/5606461/43539f00-9431-11e4-9870-f93fb85f7c0b.png)

>**Left**: {P: 0.33, I: 0.0, D: 0.0}
>**Right**: {P: 0.33, I: 0.0, D: 0.0}
![pid_033](https://cloud.githubusercontent.com/assets/6282985/5606440/31efd270-9430-11e4-8a3c-9bdf5970f0fb.png)

>**Left**: {P: 0.32, I: 0.0, D: 0.0}
>**Right**: {P: 0.32, I: 0.0, D: 0.0}
![pid_032](https://cloud.githubusercontent.com/assets/6282985/5606448/909e329e-9430-11e4-8b47-d46f6189dcd3.png)

>**Left**: {P: 0.30, I: 0.0, D: 0.0}
>**Right**: {P: 0.30, I: 0.0, D: 0.0}
![pid_030](https://cloud.githubusercontent.com/assets/6282985/5606453/d43e3224-9430-11e4-92a5-0959e5b1142e.png)

*MUST BE NOTED DIFFERENCE FROM LEFT and RIGHT MEASURE and rapid changing of response from 0.33 and 0.32 Kp value*

If I restore original value of k_vel: 27925268.0  (it is approximately twice than my K_vel ) pid response can be ok, small chang of Kp perform small change in response, but persist a different response of right channel:
![kve_original](https://cloud.githubusercontent.com/assets/6282985/5606512/e0fd354e-9432-11e4-9d1e-d524ee1a71db.png)

Finishing, with *k_ang:  0.00017453292093705386* ( original value ) I've similar response from 2 channel:
![final](https://cloud.githubusercontent.com/assets/6282985/5606530/bfa08a80-9433-11e4-8cce-fe53b4da4762.png)

Now I open my Encoder to check configuration...

**Comment by rbonghi** [comment]
@guiott Do you remember a similar problem with your encoders in Lino robot?

@Myzhar

**Comment by rbonghi** [comment]
I think if we solve this problem we solve another issue #12

**Comment by guiott** [comment]
Yes, I remember I’ve had some problems but I don’t remember the solution.
My problem was something different. Over a particular speed it starts randomly but often generating wrong behavior, the calculated speed was 0 and it requires some cycles to come back at the right speed. This caused some bad and dangerous noises.

I’ve looked on my source code for some comment about this but with no success.


> Il giorno 04/gen/2015, alle ore 18:22, Raffaello Bonghi <notifications@github.com> ha scritto:
> 
> @guiott <https://github.com/guiott> Do you remember a similar problem with your encoders in Lino robot?
> 
> @Myzhar <https://github.com/Myzhar>
> —
> Reply to this email directly or view it on GitHub <https://github.com/officinerobotiche/uNAV.X/issues/26#issuecomment-68640703>.
> 

___________________
http://www.guiott.com/

**Comment by Myzhar** [comment]
I think this is an overflow issue. I faced similar problem tuning the pid for my robot with K_p very low.
Now, if I remember well, we are working with millirad, this takes to number too high for certain configurations.
Is it really necessary to work with millirad? I think that centirad should be enough... If not decirad. .. The pid for the dspic works in fractional, so millirad is really dangerous and unuseful.

**Comment by Myzhar** [comment]
Parsing the code I noticed that only K_vel affects the behavior of the PID.
The file involved is "motors_PID.c" at lines 303 and 330 in the functions 
int MotorPIDL(void) amd int MotorPIDR(void).

Line 303: 
if (SIG_VELLtmp) motor_left.measure_vel = SIG_VELLtmp * (parameter_motor_left.k_vel / timePeriodLtmp);

Line 330:
if (SIG_VELRtmp) motor_right.measure_vel = SIG_VELRtmp * (parameter_motor_right.k_vel / timePeriodRtmp);

I'm going to test them...

**Comment by Myzhar** [comment]
A possible fix is available in the new branch "feature/gain_scaling".
@katodo please test it and let me know if the behavior is better and how it works now

**Comment by rbonghi** [comment]
My idea is to move **K_vel** in gain loop control. 
![2015-01-10](https://cloud.githubusercontent.com/assets/4551246/5692114/a0e5082e-98e7-11e4-8d8f-5a2421e9d6ba.jpg)

If you look the pitcture, we have an equivalence when **K_B = K_vel*K_pwm** and **K_A = 1**
We now using the first schema (A)

**Comment by rbonghi** [comment]
@katodo Do you can try again your test?

**Comment by katodo** [comment]
Not soon, my problem was PID tuning related and with actual utility I need
a lot of time and concentration. I would like to avoid making mistakes again

Cordiali saluti
                        Mauro Soligo

Katodo  di Mauro Soligo
Via Molino Nuovo, 31 35012 Camposampiero PD Italy
P.IVA 04161520285  C.F. SLGMRA80L18B563Y
Cell: +39 3462137146  FAX: +39 0498591588  e-mail mauro.soligo@katodo.com

2015-01-14 11:55 GMT+01:00 Raffaello Bonghi <notifications@github.com>:

**Comment by rbonghi** [comment]
This issue is connected with #37
