### ISSUE TITLE
Split motion.h

### ISSUE THREAD

**Issue by rbonghi** [officinerobotiche/uNAV.X#31]
To be readable motion.h I would like to split `motion.h` in to files, the first one will be called `motors.h` with all command about motors (ex. motors, pid, etc etc) and second `motion.h` with all messages about movement (ex. twist, odometry, etc etc)

An a first list for `motors.h`:
1. `constraint_t`
2. `motor_t`
3. `pid_control_t`
4. `parameter_motor_t`
5. `enable_motor_t`

For `motion.h`:
1. `emergency_t`
2. `coordinate_t`
3. `parameter_unicycle_t`
4. `velocity_t` -> to be called `twist_t`

**Comment by katodo** [comment]
Ok :+1:

**Comment by bobboteck** [comment]
Good idea!

**Comment by rbonghi** [comment]
946441d16b39298b4ee3565cc16c71526bcde83c Added information about temperature
