### ISSUE TITLE
Motors do not stop after disconnection...

### ISSUE THREAD

**Issue by Myzhar** [officinerobotiche/uNAV.X#38]
When driving the motors using 
```VEL_MOTOR_L``` and ```VEL_MOTOR_R``` 
packets the stop procedure after disconnection does not work.

Looking at "Emergency" function (https://github.com/officinerobotiche/uNAV.X/blob/develop/src/control/high_level_control.c#L237) 
I noticed that it reduces the velocity according to unicycle model and not considering the rotation speed of the single motor.

The function should be changed according to the new "speed model", decreasing directly
```motor_left.refer_vel``` and ```motor_right.refer_vel```
instead of 
```vel_rif.v``` and ```vel_rif.w```

**Comment by rbonghi** [comment]
I solved this problem and add a new type of state controller `STATE_CONTROL_EMERGENCY`. When motor change on this state the motor put to zero the reference motor and finally disable motor
