### ISSUE TITLE
Motor SetPoints from int16 to int32

### ISSUE THREAD

**Issue by Myzhar** [officinerobotiche/uNAV.X#40]
Change setPoint variable type to long int to avoid limitations to 32 rad/sec

**Comment by rbonghi** [comment]
Now we can change the type of variable from `int16_t` to `int_32_t` in: 
https://github.com/officinerobotiche/uNAV.X/blob/develop/includes/packet/motor.h#L51

But I think to change the control low to control a big number compare to `int16_t` variable #37 
\cc @Myzhar

**Comment by rbonghi** [comment]
Check if required to change all `float` variable in `long double`. Following http://www.microchip.com/forums/m747574.aspx
