### ISSUE TITLE
Verify the correctness of the odometry

### ISSUE THREAD

**Issue by Myzhar** [officinerobotiche/uNAV.X#42]
As stated by voice there are issues with the odometry calculations.

We need to verify the correctness of the formulas about rotation angle.

**Comment by Myzhar** [comment]
This can be useful:
http://faculty.salina.k-state.edu/tim/robotics_sg/Control/kinematics/unicycle.html

**Comment by Myzhar** [comment]
This too:
http://www.scielo.br/scielo.php?pid=S0103-17592008000400003&script=sci_arttext

**Comment by rbonghi** [comment]
Fixed e85e8a90a58643a30d6508aca5417a0a3378e5f9
