### ISSUE TITLE
GPIO -  clone STM32 HAL structure

### ISSUE THREAD

**Issue by katodo** [officinerobotiche/uNAV.X#45]
I'm working on STM32 and I've found very interesting HAL function to GPIO access... can be interesting implementation for our code to simplify future porting :)

This file can be a usefull reference:

https://github.com/Laurenceb/STM32F3Discovery/blob/master/lib/STM32F37x_StdPeriph_Driver/src/stm32f37x_gpio.c

https://github.com/Laurenceb/STM32F3Discovery/blob/master/lib/STM32F37x_StdPeriph_Driver/inc/stm32f37x_gpio.h

**Comment by rbonghi** [comment]
Fixed e41489634624bd896dc67b838f848aff8c98bd93
